name: "Publish to Nekoweb"

on:
    push:
        branches:
            - main

jobs:
    build-and-publish:
        environment: Nekoweb
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup python
              uses: actions/setup-python@v5

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node_version: lts
            
            - uses: pnpm/action-setup@v3
              name: Install pnpm
              with:
                version: 8
                run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        
            - uses: actions/cache@v4
              name: Setup pnpm cache
              with:
                path: ${{ env.STORE_PATH }}
                key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                restore-keys: |
                    ${{ runner.os }}-pnpm-store-
        
            - name: Install dependencies
              run: pnpm install

            - name: Run publishing script
              run: python3 nekopublish.py
              env:
                NKWEB_API_TOKEN: ${{ secrets.NKWEB_API_TOKEN }}
            
